import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface":                    "#f8f9ff",
        "surface-dim":                "#cbdbf5",
        "surface-bright":             "#f8f9ff",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#eff4ff",
        "surface-container":          "#e5eeff",
        "surface-container-high":     "#dce9ff",
        "surface-container-highest":  "#d3e4fe",
        "on-surface":                 "#0b1c30",
        "on-surface-variant":         "#464554",
        "inverse-surface":            "#213145",
        "inverse-on-surface":         "#eaf1ff",
        "outline":                    "#767586",
        "outline-variant":            "#c7c4d7",
        "surface-tint":               "#494bd6",
        "primary":                    "#4648d4",
        "on-primary":                 "#ffffff",
        "primary-container":          "#6063ee",
        "on-primary-container":       "#fffbff",
        "inverse-primary":            "#c0c1ff",
        "secondary":                  "#006c49",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#6cf8bb",
        "on-secondary-container":     "#00714d",
        "tertiary":                   "#825100",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#a36700",
        "on-tertiary-container":      "#fffbff",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "primary-fixed":              "#e1e0ff",
        "primary-fixed-dim":          "#c0c1ff",
        "on-primary-fixed":           "#07006c",
        "on-primary-fixed-variant":   "#2f2ebe",
        "secondary-fixed":            "#6ffbbe",
        "secondary-fixed-dim":        "#4edea3",
        "on-secondary-fixed":         "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed":             "#ffddb8",
        "tertiary-fixed-dim":         "#ffb95f",
        "on-tertiary-fixed":          "#2a1700",
        "on-tertiary-fixed-variant":  "#653e00",
        "background":                 "#f8f9ff",
        "on-background":              "#0b1c30",
        "surface-variant":            "#d3e4fe",
      },
      fontFamily: {
        sans:    ["var(--font-sans)", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "Quicksand", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md":            ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg":            ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md":           ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "caption":            ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md":        ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg":        ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-xl":        ["48px", { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" }],
      },
      borderRadius: {
        sm:      "0.5rem",
        DEFAULT: "1rem",
        md:      "1.5rem",
        lg:      "2rem",
        xl:      "3rem",
        full:    "9999px",
      },
      spacing: {
        gutter:           "24px",
        unit:             "8px",
        "margin-mobile":  "16px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      boxShadow: {
        "soft":       "0 10px 30px -10px rgba(192, 193, 255, 0.6)",
        "soft-hover": "0 20px 40px -15px rgba(192, 193, 255, 0.9)",
        "squishy":    "0 4px 0 #2f2ebe",
        "navbar":     "0 4px 20px 0 rgba(70, 72, 212, 0.1)",
      },
    },
  },
  plugins: [],
};

export default config;
