import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      maxWidth: {
        "container-max": "1280px",
      },
      colors: {
        brand: {
          50: "#f0f7ff",
          100: "#e0effe",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          900: "#1e3a8a",
        },
        // Sanzo Wada inspired palette — deep navy + warm gold + ivory
        navy: {
          50:  "#f0f4f9",
          100: "#d9e4ef",
          200: "#b3c9df",
          300: "#7aa4c8",
          400: "#4a7fab",
          500: "#2d6491",
          600: "#1d4e78",
          700: "#163d61",
          800: "#112e4a",
          900: "#1B3A5C",
          950: "#0c1e33",
        },
        gold: {
          50:  "#fdf7e8",
          100: "#faecca",
          200: "#f5d68a",
          300: "#eeba4a",
          400: "#e5a030",
          500: "#C8962B",
          600: "#a87820",
          700: "#8a5e18",
          800: "#6e4a16",
          900: "#573b16",
        },
        ivory: "#F7F3EE",

        // New Design System Tokens
        background:                "var(--color-background)",
        "on-background":           "var(--color-on-background)",
        primary:                   "var(--color-primary)",
        "on-primary":              "var(--color-on-primary)",
        "primary-fixed":           "var(--color-primary-fixed)",
        "on-primary-fixed":        "var(--color-on-primary-fixed)",
        "primary-fixed-dim":       "var(--color-primary-fixed-dim)",
        "surface-container-lowest":"var(--color-surface-container-lowest)",
        "surface-container-low":   "var(--color-surface-container-low)",
        "surface-container":       "var(--color-surface-container)",
        "on-surface-variant":      "var(--color-on-surface-variant)",
        "outline-variant":         "var(--color-outline-variant)",
        "secondary-container":     "var(--color-secondary-container)",
        "on-secondary-container":  "var(--color-on-secondary-container)",
        secondary:                 "var(--color-secondary)",
        "error-container":         "var(--color-error-container)",
        "on-error-container":      "var(--color-on-error-container)",
        "tertiary-fixed":          "var(--color-tertiary-fixed)",
        "on-tertiary-fixed":       "var(--color-on-tertiary-fixed)",
        "inverse-surface":         "var(--color-inverse-surface)",
        "inverse-on-surface":      "var(--color-inverse-on-surface)",
        "on-primary-fixed-variant":"var(--color-on-primary-fixed-variant)",
        "primary-container":       "var(--color-primary-container)",
        "on-primary-container":    "var(--color-on-primary-container)",
        "secondary-fixed":         "var(--color-secondary-fixed)",
        surface:                   "var(--color-surface)",
        "on-surface":              "var(--color-on-surface)",
        "surface-variant":         "var(--color-surface-variant)",
        "surface-container-high":  "var(--color-surface-container-high)",
        outline:                   "var(--color-outline)",
        error:                     "var(--color-error)",
        "on-error":                "var(--color-on-error)",
        sage: {
          50:  "#f0f7f4",
          100: "#d4eadf",
          200: "#a9d4bf",
          300: "#72b598",
          400: "#4a9175",
          500: "#4A7A5E",
          600: "#3a6049",
          700: "#2d4d3a",
          800: "#223a2c",
          900: "#1a2d22",
        },
      },
      fontFamily: {
        serif:   ["DM Serif Display", "Georgia", "serif"],
        sans:    ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        display: ["Quicksand", "Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

export default config;
